"""create user model

Revision ID: 2eb8d8b42b07
Revises: 
Create Date: 2025-12-03 23:46:07.068579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb8d8b42b07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('match_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('match_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    op.drop_table('user')
    # ### end Alembic commands ###
