"""update number of charact

Revision ID: 42939816b8cb
Revises: 2eb8d8b42b07
Create Date: 2025-12-04 01:02:01.418312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42939816b8cb'
down_revision = '2eb8d8b42b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
